#!/usr/bin/env ruby
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with this
# work for additional information regarding copyright ownership.  The ASF
# licenses this file to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
# License for the specific language governing permissions and limitations under
# the License.

# Run buildr from source, specifically for testing stuff without doing a rake install.
# The _BUILDR_RB environment variable can be used to set the path to the ruby/jruby executable.
# For example to use jruby:
#   export _BUILDR_RB=/path/to/jruby

start = Time.now
require 'rubygems'
$LOAD_PATH << File.join(File.dirname(__FILE__), 'lib') << File.join(File.dirname(__FILE__), 'addon')
spec = Gem::Specification.load(File.join(File.dirname(__FILE__), 'buildr.gemspec'))
spec.dependencies.each do |dep|
  gem dep.name, dep.version_requirements.to_s
end
require 'buildr'
Buildr.application.run
if verbose
  elapsed = Time.now - start
  real = []
  real << ("%ih" % (elapsed / 3600)) if elapsed >= 3600
  real << ("%im" % ((elapsed / 60) % 60)) if elapsed >= 60
  real << ("%.3fs" % (elapsed % 60))
  puts $terminal.color("Completed in #{real.join}", :green)
end
