#!/bin/bash
# -----------------------------------------------------------------------------
# buildr.sh - Start Script for the Buildr interpreter
# -----------------------------------------------------------------------------

## resolve links - $0 may be a link to  home
PRG=$0
progname=`basename "$0"`

while [ -h "$PRG" ] ; do
  ls=`ls -ld "$PRG"`
  link=`expr "$ls" : '.*-> \(.*\)$'`
  if expr "$link" : '.*/.*' > /dev/null; then
    if expr "$link" : '/' > /dev/null; then
      PRG="$link"
    else
      PRG="`dirname ${PRG}`/${link}"
    fi
  else
    PRG="`dirname $PRG`/$link"
  fi
done

BUILDR_HOME=`dirname "$PRG"`

$BUILDR_HOME/../embedded/bin/jruby -S buildr "$@"
