# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with this
# work for additional information regarding copyright ownership.  The ASF
# licenses this file to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
# License for the specific language governing permissions and limitations under
# the License.

repositories.remote =  ["http://repo1.maven.org/maven2"]
SLF4J_API = "org.slf4j:slf4j-api:jar:1.6.1"

define "proj" do
  project.version = "1.0"
  project.group = "org.example"  
  package(:zip).include(_("doc"), :path => "distrib")
  package(:zip).include(artifact(SLF4J_API), :path => "distrib/lib")
end